//defines.h all macros
#include "types.h"

#define WRITEBYTE(WORD,STARTBIT,BYTE)\
						WORD=(WORD&(u32)~0XFF<<STARTBIT)|(BYTE<<STARTBIT)
#define WRITEBIT(WORD,BIT,BITLEVEL)\
						WORD=((WORD&(u32)~(1<<BIT))|(BITLEVEL<<BIT))
#define WRITENIBBLE(WORD,BITPOS,BYTE)\
						WORD=(WORD&(u32)~(0X0F<<BITPOS) | (BYTE<<BITPOS))
#define READBYTE(WORD,STARTBIT)((WORD>>STARTBIT)&0XFF)

#define READNIBBLE(WORD,BITPOS) ((WORD>>BITPOS)&0X0F)

#define READBIT(WORD,BIT) ((WORD>>BIT)&1)

#define READWRITEBIT(WORD, SBIT, DBIT) \
    WORD=((WORD & (u32)~(1<<DBIT)) | (((WORD>>SBIT)&1)<<DBIT))
#define CLRBIT(WORD,BIT) (WORD=(WORD&(u32)~(1<<BIT)))
#define SETBIT(WORD,BIT) (WORD=(WORD|(1<<BIT)))
